// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLYQYeewct95oHrWIldiLALIO9ql0WkHo',
    appId: '1:447915689969:web:5d188a6829e78e0e076650',
    messagingSenderId: '447915689969',
    projectId: 'flutter-chating-app-9fcc9',
    authDomain: 'flutter-chating-app-9fcc9.firebaseapp.com',
    storageBucket: 'flutter-chating-app-9fcc9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuqBqeumWlt50WPwZQ4zZgVNarUIV9GEI',
    appId: '1:447915689969:android:92dfd6190c6c30c6076650',
    messagingSenderId: '447915689969',
    projectId: 'flutter-chating-app-9fcc9',
    storageBucket: 'flutter-chating-app-9fcc9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfUP45ttJDT_A-ZMadAVaFywWhl4dMyws',
    appId: '1:447915689969:ios:434c26236775b010076650',
    messagingSenderId: '447915689969',
    projectId: 'flutter-chating-app-9fcc9',
    storageBucket: 'flutter-chating-app-9fcc9.firebasestorage.app',
    iosBundleId: 'com.example.chatingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfUP45ttJDT_A-ZMadAVaFywWhl4dMyws',
    appId: '1:447915689969:ios:434c26236775b010076650',
    messagingSenderId: '447915689969',
    projectId: 'flutter-chating-app-9fcc9',
    storageBucket: 'flutter-chating-app-9fcc9.firebasestorage.app',
    iosBundleId: 'com.example.chatingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLYQYeewct95oHrWIldiLALIO9ql0WkHo',
    appId: '1:447915689969:web:89b179a257184bbf076650',
    messagingSenderId: '447915689969',
    projectId: 'flutter-chating-app-9fcc9',
    authDomain: 'flutter-chating-app-9fcc9.firebaseapp.com',
    storageBucket: 'flutter-chating-app-9fcc9.firebasestorage.app',
  );
}
